export const BACKGROUND_ECOLOGY = {
  terrain: {
    cell: 72,
    paddingCells: 2,
    activeThreshold: 0.68,
    pebbleThreshold: 0.92,
  },
  moss: {
    cell: 144,
    paddingCells: 2,
    activeThreshold: 0.64,
    highlightThreshold: 0.86,
    minSpread: 38,
    maxSpread: 88,
    minDots: 3,
    maxDots: 12,
  },
  microGrowth: {
    cell: 360,
    paddingCells: 1,
    activeThreshold: 0.66,
    minSprouts: 1,
    maxSprouts: 5,
    minSpread: 22,
    maxSpread: 98,
    distanceExponent: 1.45,
  },
  midground: {
    cell: 250,
    paddingCells: 2,
    activeThreshold: 0.58,
    crystalThreshold: 0.72,
    sporeThreshold: 0.38,
    minFootprint: 16,
    maxFootprint: 52,
  },
  distantCrystals: {
    minCount: 2,
    maxCount: 10,
    minSpread: 10,
    maxSpread: 44,
    minHeight: 8,
    maxHeight: 48,
  },
  distantSpores: {
    minCount: 1,
    maxCount: 8,
    minSpread: 14,
    maxSpread: 56,
  },
  distantRocks: {
    minCount: 2,
    maxCount: 11,
    minSpread: 18,
    maxSpread: 64,
  },
} as const;
